version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
      COMMON_RATE_LIMIT_MAX_REQUESTS: 1000
      COMMON_RATE_LIMIT_WINDOW_MS: 1000
      CORS_ORIGIN: http://localhost:3000
      PORT: 8080
      HOST: localhost
      NODE_ENV: test

    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: